pipeline:
    build:
        image: golang
        commands:
            - env
    sonarqube:
        image: newtmitch/sonar-scanner:3.2.0-alpine
        commands:
          - >
            sonar-scanner
            -Dsonar.projectName=${DRONE_REPO_NAME}
            -Dsonar.host.url=http://sonar.relipa.blog 
            -Dsonar.projectKey=${DRONE_BRANCH} 
            -Dsonar.projectVersion=${DRONE_BUILD_NUMBER}
            -Dsonar.login=admin
            -Dsonar.password=admin
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.host.url=http://sonar.relipa.blog
            -Dsonar.analysis.mode=preview
            -Dsonar.github.repository=dienncrelipa/test
            -Dsonar.github.pullRequest=${DRONE_PULL_REQUEST}
            -Dsonar.verbose=true
            -Dsonar.github.login=dienncrelipa
            -Dsonar.github.oauth=a4c68bcd996ca9f43cb4be77e206f334891ba35e
