pipeline:
    build:
        image: golang
        commands:
            - env
    sonarqube:
        image: newtmitch/sonar-scanner
        commands:
          - >
            sonar-scanner
            -Dsonar.projectName=${DRONE_REPO_NAME}
            -Dsonar.host.url=http://sonar.relipa.blog 
            -Dsonar.projectKey=${DRONE_BRANCH} 
            -Dsonar.projectVersion=${DRONE_BUILD_NUMBER}
            -Dsonar.login=admin
            -Dsonar.password=admin
            -Dsonar.projectBaseDir=.
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.host.url=http://sonar.relipa.blog
            -Dsonar.analysis.mode=preview
            -Dsonar.github.repository=dienncrelipa/test
            -Dsonar.github.pullRequest=${DRONE_PULL_REQUEST}
            -Dsonar.verbose=true
            -Dsonar.github.login=dienncrelipa
            -Dsonar.github.oauth=c74afec118ea6dd40af42f37185146165e20a3b6
trigger:
    event:
      - pull_request
