pipeline:
    build:
        image: golang
        commands:
            - env
    sonarqube:
        image: newtmitch/sonar-scanner
        commands:
          - >
            sonar-scanner
            -Dsonar.projectName="API (${DRONE_BRANCH})"
            -Dsonar.host.url=http://sonar.relipa.blog
            -Dsonar.projectKey=api:${DRONE_BRANCH}
            -Dsonar.projectVersion=$(cat VERSION)
            -Dsonar.projectBaseDir=.
            -Dsonar.login=admin
            -Dsonar.password=admin
            -Dsonar.sources=.
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.host.url=http://sonar.relipa.blog
            -Dsonar.analysis.mode=preview
            -Dsonar.github.repository=dienncrelipa/test
            -Dsonar.github.pullRequest=${DRONE_PULL_REQUES}
            -Dsonar.verbose=true
            -Dsonar.github.login=dienncrelipa
            -Dsonar.github.oauth=7ba7df34fb9777009601836df88b3d5592bba161
