pipeline:
    build:
        image: golang
        commands:
            - env
    sonarqube:
        image: newtmitch/sonar-scanner
        commands:
          - >
            sonar-scanner -D /drone/src/github.com/dienncrelipa/test/sonar-project.properties
trigger:
    event:
      - pull_request
