pipeline:
    code-analysis:
        image: aosapps/drone-sonar-plugin
        secrets: ['http://sonar.relipa.blog','65c225516f8b3635a2722bd8743bfe7ac80109b0']
        sources: ./
        showProfiling: true
    build:
        image: golang
        commands:
            - env
