pipeline:
    build:
        image: golang
        commands:
            - env
    sonarqube:
        image: newtmitch/sonar-scanner
        commands:
          - >
            sonar-scanner
trigger:
    event:
      - pull_request
