pipeline:
     code-analysis:
         image: aosapps/drone-sonar-plugin
         secrets: [http://sonar.relipa.blog,65c225516f8b3635a2722bd8743bfe7ac80109b0]
         ver: 1.0
         timeout: 20
         sources: .
         level: DEBUG
         showProfiling: true
pipeline:
     build:
         image: golang
         commands:
             - env
